apiVersion: v1
kind: Service
metadata:
    name: "test-7c31"
    labels:
        app: "test-7c31"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "test-7c31"