podTemplate(label: "mynode", 
yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: rafabene/jenkins-slave
    imagePullPolicy: IfNotPresent
    tty: true
    command: ["cat"]
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    - name: m2
      mountPath: /root/.m2
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: m2
    hostPath:
      path: /tmp/m2
"""
  ) {
    properties([pipelineTriggers([pollSCM('*/1 * * * * ')])])
    node ("mynode"){
        
        container("maven"){
           stage ('SCM checkout'){
                echo 'Checking out git repository'
                git poll: true, url: 'https://github.com/rafabene/microservices4demo'
            }
        
            stage ('Install node module'){
                echo 'Running npm install'
                dir('ola') {
                    sh 'npm install'
                }       
            }

            stage ('Docker image build'){
                echo 'Building docker image'
                dir('ola') {
                    sh 'docker build -t rafabene/ms4demo:node .'
                }       
            }

            stage ('Perform Tests'){
                echo 'Building native binary'
                dir('ola') {
                    sh 'npm test'
                }       
            }
            
            stage ('Wait for approval'){
                input 'Approve deployment?'
            }

            stage ('Deploy'){
                echo 'Building native binary'
                dir('ola') {
                    sh 'kubectl create namespace microservices || echo "Namespace \"microservices\" already exists"'
                    sh 'kubectl apply -f kubernetes/deployment-v2.yaml'
                    sh 'kubectl apply -f kubernetes/deployment.yaml'
                    sh 'kubectl apply -f kubernetes/service.yaml'
                    sh """kubectl patch deployment hello -n microservices -p '{"spec":{"template":{"metadata":{"labels":{ "build": "${env.BUILD_NUMBER}"}}}}}' """
                }       
            }
        }    
    }
}
